doctrine:
    dbal:
        driver: pdo_mysql
        server_version: 5.7
        host: 127.0.0.1
        port: 3306
        dbname: bebeco
        user: root
        password: root
        charset: UTF8
        schema_filter: ~^(?!fos_)~
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Building:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Simulator/Infrastructure/Building/Persistence/Doctrine'
                prefix: 'App\Simulator\Domain\Building\Model'
                alias: Building
            Elevator:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Simulator/Infrastructure/Elevator/Persistence/Doctrine'
                prefix: 'App\Simulator\Domain\Elevator\Model'
                alias: Elevator
            Sequence:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Simulator/Infrastructure/Sequence/Persistence/Doctrine'
                prefix: 'App\Simulator\Domain\Sequence\Model'
                alias: Sequence
            Report:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Simulator/Infrastructure/Report/Persistence/Doctrine'
                prefix: 'App\Simulator\Domain\Report\Model'
                alias: Report