framework:
    messenger:
        default_bus: query.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus:
                middleware:
                    - doctrine_transaction
