version: "3"
services:
  mysql:
    container_name: bebeco-mysql-development
    image: mysql:5.7.12
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bebeco
    volumes:
      - ../etc/build/config/mysql/:/etc/mysql/conf.d
      - bebeco-mysql-dev:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
        - bebeco_development

networks:
    bebeco_development:
volumes:
    bebeco-mysql-dev:
