# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(DATABASE_NAME): 'bebeco'
    env(DATABASE_HOST): '127.0.0.1'
    env(DATABASE_PORT): '3306'
    env(DATABASE_USER): 'root'
    env(DATABASE_PASSWORD): 'root'
    env(DATABASE_DRIVER): 'pdo_mysql'
    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Simulator\UI\Web\Controller\:
        resource: '../src/Simulator/UI/Web/Controller/*'
        tags: [ 'controller.service_arguments' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    command_handlers:
        namespace: App\Simulator\Application\Command\
        resource: '%kernel.project_dir%/src/Simulator/Application/Command/*/*CommandHandler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    query_handlers:
        namespace: App\Simulator\Application\Query\
        resource: '%kernel.project_dir%/src/Simulator/Application/Query/*/*QueryHandler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: query.bus }
